import { ChevronDown, Star } from 'lucide-react';
import { useState } from 'react';
import { Checkbox } from '@/components/ui/checkbox'
import { Tabs, TabsContent, TabsList, TabsTrigger, tabsListVariants } from '@/components/ui/tabs'
import { cn } from '@/lib/utils'
import { format } from '@/utils/format';
import { products } from '@/config/mockProducts';
import { Badge } from '@/components/ui/badge';

// These Initial orders  dummy data are generated by AI
const INITIAL_ORDERS = [
    { orderId: "ORD-001", customerName: "Mariana Voss", items: [{ productId: "P1", productName: "Canvas Tote", quantity: 2, price: 29.99, customizations: [{ optionGroupId: "cg1", groupName: "Color", options: ["Sage Green"] }] }, { productId: "P2", productName: "Linen Scarf", quantity: 1, price: 49.99 }], totalAmount: 109.97, paymentMethod: "Online", paymentStatus: "Paid", orderStatus: "Shipped", shippingAddress: "42 Birchwood Lane, Portland, OR 97201", createdAt: "2025-01-15T10:22:00Z" },
    { orderId: "ORD-002", customerName: "Theo Nakamura", items: [{ productId: "P3", productName: "Ceramic Mug Set", quantity: 1, price: 64.00 }], totalAmount: 64.00, paymentMethod: "COD", paymentStatus: "Pending", orderStatus: "Pending", shippingAddress: "7 Elm Street, Austin, TX 78701", createdAt: "2025-01-17T14:05:00Z" },
    { orderId: "ORD-003", customerName: "Sienna Okafor", items: [{ productId: "P4", productName: "Woven Basket", quantity: 3, price: 22.50, customizations: [{ optionGroupId: "cg2", groupName: "Size", options: ["Large"] }, { optionGroupId: "cg3", groupName: "Handle", options: ["Leather Wrap"] }] }], totalAmount: 67.50, paymentMethod: "Online", paymentStatus: "Paid", orderStatus: "Delivered", shippingAddress: "881 Oak Ave, Brooklyn, NY 11201", createdAt: "2025-01-10T09:18:00Z" },
    { orderId: "ORD-004", customerName: "Lucien Breault", items: [{ productId: "P5", productName: "Beeswax Candle", quantity: 4, price: 15.00 }, { productId: "P6", productName: "Matches Box", quantity: 2, price: 8.00 }], totalAmount: 76.00, paymentMethod: "Online", paymentStatus: "Failed", orderStatus: "Cancelled", shippingAddress: "33 Maple Dr, Vancouver, BC V5K 0A1", createdAt: "2025-01-19T16:45:00Z" },
    { orderId: "ORD-005", customerName: "Amara Singh", items: [{ productId: "P1", productName: "Canvas Tote", quantity: 1, price: 29.99 }], totalAmount: 29.99, paymentMethod: "Online", paymentStatus: "Paid", orderStatus: "Pending", shippingAddress: "15 Cedar Court, Seattle, WA 98101", createdAt: "2025-01-20T08:30:00Z" },
];

const tableColumns = {
    orders: [
        'Order Id', 'Customer', 'Items', 'Total', 'Payment', 'Status'
    ],
    products: [
        'Product Id', 'Product', 'Category', 'Price', 'Unit', 'Stock', 'Status'
    ],
    users: [
        'User Id', 'Username', 'Email', 'Phone number', 'Orders', 'Total Spent'
    ]
}

function DataManagement() {
    const [activeTab, setActiveTab] = useState<keyof typeof tableColumns>('orders');

    const [selectedItems, setSelectedItems] = useState({
        orders: new Set<string>(),
        products: new Set<string>(),
        users: new Set<string>(),
    });

    const toggleSelect = (id: string, tab: keyof typeof tableColumns) => {
        setSelectedItems(prev => {
            const next = { ...prev, [tab]: new Set(prev[tab]) };
            next[tab].has(id) ? next[tab].delete(id) : next[tab].add(id);
            return next;
        });
    };

    const toggleSelectAll = (items: Array<string>, tab: keyof typeof tableColumns) => {
        setSelectedItems(prev => {
            const next = { ...prev, [tab]: new Set(prev[tab]) };
            next[tab].size === items.length ? next[tab].clear() : items.forEach(i => next[tab].add(i));
            return next;
        });
    };

    const ActionButtons = ({ tab }: { tab: keyof typeof tableColumns }) => {
        const selectedCount = selectedItems[tab].size;
        return (
            <div className="flex gap-2">
                {selectedCount === 1 && <button className={cn(tabsListVariants(), "px-2 text-sm")}>View</button>}
                {selectedCount >= 1 && (
                    <>
                        <button className={cn(tabsListVariants(), "px-2 text-sm")}>Edit</button>
                        <button className={cn(tabsListVariants(), "px-2 text-sm")}>Delete</button>
                    </>
                )}
                <button className={cn(tabsListVariants(), "px-2 text-sm")}>Add Products +</button>
            </div>
        );
    };


    return (
        <Tabs id='Data Managing Dashboard' defaultValue={activeTab}>
            <div className="flex flex-row items-center justify-between">
                <TabsList>
                    {(['orders', 'products', 'users'] as const).map(tab => (
                        <TabsTrigger key={tab} value={tab} onClick={() => setActiveTab(tab)}>
                            {tab[0].toUpperCase() + tab.slice(1)}
                        </TabsTrigger>
                    ))}
                </TabsList>
                <div className="flex flex-row items-center justify-center gap-2">
                    <ActionButtons tab={activeTab} />
                </div>
            </div>
            <TabsContent value='orders'>
                <OrdersTable
                    selectedItems={selectedItems.orders}
                    toggleSelect={(id) => toggleSelect(id, 'orders')}
                    toggleSelectAll={(ids) => toggleSelectAll(ids, 'orders')}
                />
            </TabsContent>
            <TabsContent value='products'>
                <ProductsTable
                    selectedItems={selectedItems.products}
                    toggleSelect={(id) => toggleSelect(id, 'products')}
                    toggleSelectAll={(ids) => toggleSelectAll(ids, 'products')}
                />
            </TabsContent>
            <TabsContent value='users'>
                <UsersTable
                    selectedItems={selectedItems.users}
                    toggleSelect={(id) => toggleSelect(id, 'users')}
                    toggleSelectAll={(ids) => toggleSelectAll(ids, 'users')}
                />
            </TabsContent>
        </Tabs>
    )
}

function OrdersTable({
    selectedItems,
    toggleSelect,
    toggleSelectAll,
}: {
    selectedItems: Set<string>,
    toggleSelect: (id: string) => void,
    toggleSelectAll: (ids: Array<string>) => void,
}) {
    const [expandedRows, setExpandedRows] = useState<Set<string>>(new Set())

    const toggleRow = (id: string) =>
        setExpandedRows((prev) => {
            const next = new Set(prev);
            next.has(id) ? next.delete(id) : next.add(id);
            return next;
        });

    const allIds = INITIAL_ORDERS.map(order => order.orderId);

    return (
        <table className='w-full'>
            <thead className='bg-gray-50'>
                <tr>
                    <th className='w-10 px-6 py-3 text-left text-xs font-medium uppercase text-gray-600 tracking-wide'>
                        <Checkbox className='cursor-pointer' checked={selectedItems.size === INITIAL_ORDERS.length} onCheckedChange={() => toggleSelectAll(allIds)} />
                    </th>
                    {tableColumns.orders.map((column) => (
                        <th key={`Orders-column-${column}`} className='px-6 py-3 text-left text-xs font-medium uppercase text-gray-600 tracking-wide'>{column}</th>
                    ))}
                </tr>
            </thead>
            <tbody className='divide-y divide-gray-200'>
                {
                    INITIAL_ORDERS.map(order => {
                        const isExpanded = expandedRows.has(order.orderId)
                        const isSelected = selectedItems.has(order.orderId)

                        return (
                            <>
                                <tr className='hover:bg-yellow-50'>
                                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900 flex items-center gap-2">
                                        <Checkbox className='cursor-pointer' checked={isSelected} onCheckedChange={() => toggleSelect(order.orderId)} />
                                        <button
                                            type="button"
                                            onClick={() => toggleRow(order.orderId)}
                                            className="flex items-center justify-center w-6 h-6 rounded-md text-gray-400 hover:text-gray-700 hover:bg-gray-100 transition-colors cursor-pointer"
                                            aria-expanded={isExpanded}
                                        >
                                            <ChevronDown
                                                size={14}
                                                style={{
                                                    transform: isExpanded ? "rotate(180deg)" : "rotate(0deg)",
                                                    transition: "transform 320ms cubic-bezier(0.4, 0, 0.2, 1)",
                                                }}
                                            />
                                        </button>
                                    </td>
                                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900">{order.orderId}</td>
                                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900">{order.customerName}</td>
                                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900">{order.items.length} item{order.items.length !== 1 ? "s" : ""}</td>
                                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900">{format.currency(order.totalAmount)}</td>
                                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900">{order.paymentMethod} (<span>{order.paymentStatus}</span>)</td>
                                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900">{order.orderStatus}</td>
                                </tr>

                                {isExpanded && (
                                    <tr key={`${order.orderId}-expanded`} className="">
                                        <td colSpan={7} className="px-6 py-5">
                                            <div className="grid grid-cols-1 gap-5">
                                                <div>
                                                    <p className="text-xs font-semibold uppercase tracking-wider mb-2">Items</p>
                                                    <div className="space-y-2">
                                                        {order.items.map(item => (
                                                            <div key={item.productId} className="flex items-start gap-3 bg-white rounded-lg p-3 border border-gray-100">
                                                                <div className="flex-1">
                                                                    <div className="flex items-center gap-2">
                                                                        <span className="text-sm font-medium">{item.productName}</span>
                                                                        <span className="text-zinc-700 text-xs">x{item.quantity}</span>
                                                                        <span className="text-xs ml-auto">{format.currency(item.price * item.quantity)}</span>
                                                                    </div>
                                                                    {item.customizations && item.customizations.length > 0 && (
                                                                        <div className="flex flex-wrap gap-1.5 mt-1.5">
                                                                            {item.customizations.map(customizationGroup => (
                                                                                <span key={customizationGroup.optionGroupId} className="text-xs bg-yellow-500/60 px-2 py-0.5 rounded-full">
                                                                                    {customizationGroup.groupName}: {customizationGroup.options.join(", ")}
                                                                                </span>
                                                                            ))}
                                                                        </div>
                                                                    )}
                                                                </div>
                                                            </div>
                                                        ))}
                                                    </div>
                                                </div>

                                                <div className="grid grid-cols-2 gap-4">
                                                    <div>
                                                        <p className="text-xs font-semibold uppercase tracking-wider mb-2">Shipping Address</p>
                                                        <p className="text-gray-700 text-sm">{order.shippingAddress}</p>
                                                        <button className="mt-2 text-xs text-yellow-900 transition-colors flex items-center gap-1 cursor-pointer">
                                                            <svg className="w-3 h-3" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 20l-5.447-2.724A1 1 0 013 16.382V5.618a1 1 0 011.447-.894L9 7m0 13l6-3m-6 3V7m6 10l4.553 2.276A1 1 0 0021 18.382V7.618a1 1 0 00-.553-.894L15 4m0 13V4m0 0L9 7" /></svg>
                                                            View on Map
                                                        </button>
                                                    </div>
                                                    <div>
                                                        <p className="text-xs font-semibold uppercase tracking-wider mb-2">Metadata</p>
                                                        <div className="space-y-1 text-xs">
                                                            <div className="text-gray-700 flex gap-2"><span className="">Placed</span><span>{format.date(order.createdAt)} at {format.time(order.createdAt)}</span></div>
                                                            <div className="text-gray-700 flex gap-2"><span className="">Method</span><span>{order.paymentMethod}</span></div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </td>
                                    </tr>
                                )}
                            </>
                        )
                    })
                }
            </tbody>
        </table>
    )
}

function ProductsTable({
    selectedItems,
    toggleSelect,
    toggleSelectAll,
}: {
    selectedItems: Set<string>,
    toggleSelect: (id: string) => void,
    toggleSelectAll: (ids: Array<string>) => void,
}) {
    const [expandedRows, setExpandedRows] = useState(new Set())

    const toggleRow = (id: string) =>
        setExpandedRows((prev) => {
            const next = new Set(prev);
            next.has(id) ? next.delete(id) : next.add(id);
            return next;
        });

    const allIds = products.map(product => product.productId);


    return (
        <table className='w-full'>
            <thead className='bg-gray-50'>
                <tr>
                    <th className='w-10 px-6 py-3 text-left text-xs font-medium uppercase text-gray-600 tracking-wide'>
                        <Checkbox className='cursor-pointer' checked={selectedItems.size === products.length} onCheckedChange={() => toggleSelectAll(allIds)} />
                    </th>
                    {tableColumns.products.map((column) => (
                        <th key={`Products-column-${column}`} className='px-6 py-3 text-left text-xs font-medium uppercase text-gray-600 tracking-wide'>{column}</th>
                    ))}
                </tr>
            </thead>
            <tbody className='divide-y divide-gray-200'>
                {
                    products.map(product => {
                        const isExpanded = expandedRows.has(product.productId)
                        const isSelected = selectedItems.has(product.productId)

                        return (
                            <>
                                <tr className='hover:bg-yellow-50'>
                                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900 flex items-center gap-2">
                                        <Checkbox className='cursor-pointer' checked={isSelected} onCheckedChange={() => toggleSelect(product.productId)} />
                                        <button
                                            type="button"
                                            onClick={() => toggleRow(product.productId)}
                                            className="flex items-center justify-center w-6 h-6 rounded-md text-gray-400 hover:text-gray-700 hover:bg-gray-100 transition-colors cursor-pointer"
                                            aria-expanded={isExpanded}
                                        >
                                            <ChevronDown
                                                size={14}
                                                style={{
                                                    transform: isExpanded ? "rotate(180deg)" : "rotate(0deg)",
                                                    transition: "transform 320ms cubic-bezier(0.4, 0, 0.2, 1)",
                                                }}
                                            />
                                        </button>
                                    </td>
                                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900">{product.productId}</td>
                                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900">{product.productName}</td>
                                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900">{product.category}</td>
                                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900">{format.currency(product.productPrice ?? 0)} <span className='line-through text-gray-400 text-sm'>{product.originalPrice}</span></td>
                                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900">per {product.unit ?? "unit"}</td>
                                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900">{product.lowStockThreshold ? "Low Stock" : product.inStock ? "In Stock" : "Out of Stock"}</td>
                                    <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-900">{product.isFeatured ? "Featured" : product.isActive ? "Active" : "Not-Active"}</td>
                                </tr>

                                {isExpanded && (
                                    <tr key={`${product.productId}-expanded`} className="">
                                        <td colSpan={7} className="px-6 py-5">
                                            <div className="grid grid-cols-1 gap-5">
                                                <div>
                                                    <p className="text-xs font-semibold uppercase tracking-wider mb-2">Customizations</p>
                                                    <div className="space-y-2">

                                                        {product.customizations && product.customizations.length > 0 && (
                                                            <div className="flex flex-wrap gap-1.5 mt-1.5">
                                                                {product.customizations.map(customizationGroup => (
                                                                    <span key={customizationGroup.title} className="text-xs bg-yellow-500/60 px-2 py-0.5 rounded-full">
                                                                        {customizationGroup.title}:{" "}
                                                                        {customizationGroup.options
                                                                            .map(option =>
                                                                                option.additionalPrice > 0
                                                                                    ? `${option.label} (+${format.currency(option.additionalPrice)})`
                                                                                    : option.label
                                                                            )
                                                                            .join(", ")
                                                                        }

                                                                    </span>
                                                                ))}
                                                            </div>
                                                        )}
                                                    </div>
                                                </div>

                                                <div className="grid grid-cols-2 gap-4">
                                                    <div>
                                                        <p className="text-xs font-semibold uppercase tracking-wider mb-2">Description</p>
                                                        <p className="text-gray-700 text-sm">{product.description}</p>
                                                        <Badge
                                                            variant="secondary"
                                                            className="mt-2 ml-auto bg-yellow-100 text-yellow-700 hover:bg-yellow-100 font-bold h-7"
                                                        >
                                                            <Star className="h-3 w-3 mr-1 fill-yellow-700" />
                                                            {product.rating?.toFixed(1) || "0"}
                                                        </Badge>
                                                    </div>
                                                    <div>
                                                        <p className="text-xs font-semibold uppercase tracking-wider mb-2">Metadata</p>
                                                        <div className="space-y-1 text-xs">
                                                            <div className="text-gray-700 flex gap-2"><span className="">Updated: </span><span>{format.date(product.updatedAt ?? "")} at {format.time(product.updatedAt ?? "")}</span></div>
                                                            <div className="text-gray-700 flex gap-2"><span className="">Label: </span><span>{product.label}</span></div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </td>
                                    </tr>
                                )}
                            </>
                        )
                    })
                }
            </tbody>
        </table>
    )
}

function UsersTable({
    selectedItems,
    toggleSelect,
    toggleSelectAll,
}: {
    selectedItems: Set<string>,
    toggleSelect: (id: string) => void,
    toggleSelectAll: (ids: Array<string>) => void,
}) {
    const [expandedRows, setExpandedRows] = useState(new Set())

    const toggleRow = (id: string) =>
        setExpandedRows((prev) => {
            const next = new Set(prev);
            next.has(id) ? next.delete(id) : next.add(id);
            return next;
        });

    const allIds = ["123", "124", "125"];

    return (
        <table className='w-full'>
            <thead className='bg-gray-50'>
                <tr>
                    <th className='w-10 px-6 py-3 text-left text-xs font-medium uppercase text-gray-600 tracking-wide'>
                        <Checkbox checked={selectedItems.size === allIds.length} onCheckedChange={() => toggleSelectAll(allIds)} />
                    </th>
                    {tableColumns.users.map(column => (
                        <th key={`Users-column-${column}`} className='px-6 py-3 text-left text-xs font-medium uppercase text-gray-600 tracking-wide'>{column}</th>
                    ))}
                </tr>
            </thead>
            <tbody className='divide-y divide-gray-200'>
                <tr className='hover:bg-yellow-50'>
                    <td className='px-6 py-4 whitespace-nowrap text-sm text-gray-900 flex items-center gap-2'>
                        <Checkbox checked={selectedItems.has("123")} onCheckedChange={() => toggleSelect("123")} />
                        <button
                            type="button"
                            onClick={() => toggleRow("123")}
                            className="flex items-center justify-center w-6 h-6 rounded-md text-gray-400 hover:text-gray-700 hover:bg-gray-100 transition-colors cursor-pointer"
                            aria-expanded={false}
                        >
                            <ChevronDown
                                size={14}
                                style={{
                                    transform: false ? "rotate(180deg)" : "rotate(0deg)",
                                    transition: "transform 320ms cubic-bezier(0.4, 0, 0.2, 1)",
                                }}
                            />
                        </button>
                    </td>
                    <td className='px-6 py-4 whitespace-nowrap text-sm text-gray-900'>123</td>
                    <td className='px-6 py-4 whitespace-nowrap text-sm text-gray-900'>Rahul</td>
                    <td className='px-6 py-4 whitespace-nowrap text-sm text-gray-900'>rahul@gmail.com</td>
                    <td className='px-6 py-4 whitespace-nowrap text-sm text-gray-900'>980000</td>
                    <td className='px-6 py-4 whitespace-nowrap text-sm text-gray-900'>30</td>
                    <td className='px-6 py-4 whitespace-nowrap text-sm text-gray-900'>Rs. 9000</td>
                </tr>
            </tbody>
        </table>
    );
}

export default DataManagement