/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductIndexRouteImport } from './routes/product/index'
import { Route as FavouriteIndexRouteImport } from './routes/favourite/index'
import { Route as CheckoutIndexRouteImport } from './routes/checkout/index'
import { Route as ProductProductIdRouteImport } from './routes/product/$productId'
import { Route as AuthAuthenticateRouteImport } from './routes/_auth/authenticate'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIndexRoute = ProductIndexRouteImport.update({
  id: '/product/',
  path: '/product/',
  getParentRoute: () => rootRouteImport,
} as any)
const FavouriteIndexRoute = FavouriteIndexRouteImport.update({
  id: '/favourite/',
  path: '/favourite/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutIndexRoute = CheckoutIndexRouteImport.update({
  id: '/checkout/',
  path: '/checkout/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductProductIdRoute = ProductProductIdRouteImport.update({
  id: '/product/$productId',
  path: '/product/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAuthenticateRoute = AuthAuthenticateRouteImport.update({
  id: '/_auth/authenticate',
  path: '/authenticate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/authenticate': typeof AuthAuthenticateRoute
  '/product/$productId': typeof ProductProductIdRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/favourite/': typeof FavouriteIndexRoute
  '/product/': typeof ProductIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/authenticate': typeof AuthAuthenticateRoute
  '/product/$productId': typeof ProductProductIdRoute
  '/checkout': typeof CheckoutIndexRoute
  '/favourite': typeof FavouriteIndexRoute
  '/product': typeof ProductIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth/authenticate': typeof AuthAuthenticateRoute
  '/product/$productId': typeof ProductProductIdRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/favourite/': typeof FavouriteIndexRoute
  '/product/': typeof ProductIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/authenticate'
    | '/product/$productId'
    | '/checkout/'
    | '/favourite/'
    | '/product/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/authenticate'
    | '/product/$productId'
    | '/checkout'
    | '/favourite'
    | '/product'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/_auth/authenticate'
    | '/product/$productId'
    | '/checkout/'
    | '/favourite/'
    | '/product/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthAuthenticateRoute: typeof AuthAuthenticateRoute
  ProductProductIdRoute: typeof ProductProductIdRoute
  CheckoutIndexRoute: typeof CheckoutIndexRoute
  FavouriteIndexRoute: typeof FavouriteIndexRoute
  ProductIndexRoute: typeof ProductIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/': {
      id: '/product/'
      path: '/product'
      fullPath: '/product/'
      preLoaderRoute: typeof ProductIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favourite/': {
      id: '/favourite/'
      path: '/favourite'
      fullPath: '/favourite/'
      preLoaderRoute: typeof FavouriteIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/': {
      id: '/checkout/'
      path: '/checkout'
      fullPath: '/checkout/'
      preLoaderRoute: typeof CheckoutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$productId': {
      id: '/product/$productId'
      path: '/product/$productId'
      fullPath: '/product/$productId'
      preLoaderRoute: typeof ProductProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/authenticate': {
      id: '/_auth/authenticate'
      path: '/authenticate'
      fullPath: '/authenticate'
      preLoaderRoute: typeof AuthAuthenticateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthAuthenticateRoute: AuthAuthenticateRoute,
  ProductProductIdRoute: ProductProductIdRoute,
  CheckoutIndexRoute: CheckoutIndexRoute,
  FavouriteIndexRoute: FavouriteIndexRoute,
  ProductIndexRoute: ProductIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
