/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PaymentSuccessRouteImport } from './routes/payment-success'
import { Route as PaymentFailedRouteImport } from './routes/payment-failed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductIndexRouteImport } from './routes/product/index'
import { Route as OrderIndexRouteImport } from './routes/order/index'
import { Route as FavouriteIndexRouteImport } from './routes/favourite/index'
import { Route as CheckoutIndexRouteImport } from './routes/checkout/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ProductProductIdRouteImport } from './routes/product/$productId'
import { Route as AuthAuthenticateRouteImport } from './routes/_auth/authenticate'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiPaymentEsewaSuccessRouteImport } from './routes/api/payment/esewa/success'
import { Route as ApiPaymentEsewaFailureRouteImport } from './routes/api/payment/esewa/failure'

const PaymentSuccessRoute = PaymentSuccessRouteImport.update({
  id: '/payment-success',
  path: '/payment-success',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentFailedRoute = PaymentFailedRouteImport.update({
  id: '/payment-failed',
  path: '/payment-failed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIndexRoute = ProductIndexRouteImport.update({
  id: '/product/',
  path: '/product/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderIndexRoute = OrderIndexRouteImport.update({
  id: '/order/',
  path: '/order/',
  getParentRoute: () => rootRouteImport,
} as any)
const FavouriteIndexRoute = FavouriteIndexRouteImport.update({
  id: '/favourite/',
  path: '/favourite/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutIndexRoute = CheckoutIndexRouteImport.update({
  id: '/checkout/',
  path: '/checkout/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductProductIdRoute = ProductProductIdRouteImport.update({
  id: '/product/$productId',
  path: '/product/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAuthenticateRoute = AuthAuthenticateRouteImport.update({
  id: '/_auth/authenticate',
  path: '/authenticate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentEsewaSuccessRoute = ApiPaymentEsewaSuccessRouteImport.update({
  id: '/api/payment/esewa/success',
  path: '/api/payment/esewa/success',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentEsewaFailureRoute = ApiPaymentEsewaFailureRouteImport.update({
  id: '/api/payment/esewa/failure',
  path: '/api/payment/esewa/failure',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/payment-failed': typeof PaymentFailedRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/authenticate': typeof AuthAuthenticateRoute
  '/product/$productId': typeof ProductProductIdRoute
  '/admin/': typeof AdminIndexRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/favourite/': typeof FavouriteIndexRoute
  '/order/': typeof OrderIndexRoute
  '/product/': typeof ProductIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/payment/esewa/failure': typeof ApiPaymentEsewaFailureRoute
  '/api/payment/esewa/success': typeof ApiPaymentEsewaSuccessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/payment-failed': typeof PaymentFailedRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/authenticate': typeof AuthAuthenticateRoute
  '/product/$productId': typeof ProductProductIdRoute
  '/admin': typeof AdminIndexRoute
  '/checkout': typeof CheckoutIndexRoute
  '/favourite': typeof FavouriteIndexRoute
  '/order': typeof OrderIndexRoute
  '/product': typeof ProductIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/payment/esewa/failure': typeof ApiPaymentEsewaFailureRoute
  '/api/payment/esewa/success': typeof ApiPaymentEsewaSuccessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/payment-failed': typeof PaymentFailedRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/_auth/authenticate': typeof AuthAuthenticateRoute
  '/product/$productId': typeof ProductProductIdRoute
  '/admin/': typeof AdminIndexRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/favourite/': typeof FavouriteIndexRoute
  '/order/': typeof OrderIndexRoute
  '/product/': typeof ProductIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/payment/esewa/failure': typeof ApiPaymentEsewaFailureRoute
  '/api/payment/esewa/success': typeof ApiPaymentEsewaSuccessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/payment-failed'
    | '/payment-success'
    | '/authenticate'
    | '/product/$productId'
    | '/admin/'
    | '/checkout/'
    | '/favourite/'
    | '/order/'
    | '/product/'
    | '/api/auth/$'
    | '/api/payment/esewa/failure'
    | '/api/payment/esewa/success'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/payment-failed'
    | '/payment-success'
    | '/authenticate'
    | '/product/$productId'
    | '/admin'
    | '/checkout'
    | '/favourite'
    | '/order'
    | '/product'
    | '/api/auth/$'
    | '/api/payment/esewa/failure'
    | '/api/payment/esewa/success'
  id:
    | '__root__'
    | '/'
    | '/payment-failed'
    | '/payment-success'
    | '/_auth/authenticate'
    | '/product/$productId'
    | '/admin/'
    | '/checkout/'
    | '/favourite/'
    | '/order/'
    | '/product/'
    | '/api/auth/$'
    | '/api/payment/esewa/failure'
    | '/api/payment/esewa/success'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PaymentFailedRoute: typeof PaymentFailedRoute
  PaymentSuccessRoute: typeof PaymentSuccessRoute
  AuthAuthenticateRoute: typeof AuthAuthenticateRoute
  ProductProductIdRoute: typeof ProductProductIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  CheckoutIndexRoute: typeof CheckoutIndexRoute
  FavouriteIndexRoute: typeof FavouriteIndexRoute
  OrderIndexRoute: typeof OrderIndexRoute
  ProductIndexRoute: typeof ProductIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiPaymentEsewaFailureRoute: typeof ApiPaymentEsewaFailureRoute
  ApiPaymentEsewaSuccessRoute: typeof ApiPaymentEsewaSuccessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/payment-success': {
      id: '/payment-success'
      path: '/payment-success'
      fullPath: '/payment-success'
      preLoaderRoute: typeof PaymentSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-failed': {
      id: '/payment-failed'
      path: '/payment-failed'
      fullPath: '/payment-failed'
      preLoaderRoute: typeof PaymentFailedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/': {
      id: '/product/'
      path: '/product'
      fullPath: '/product/'
      preLoaderRoute: typeof ProductIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/': {
      id: '/order/'
      path: '/order'
      fullPath: '/order/'
      preLoaderRoute: typeof OrderIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favourite/': {
      id: '/favourite/'
      path: '/favourite'
      fullPath: '/favourite/'
      preLoaderRoute: typeof FavouriteIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/': {
      id: '/checkout/'
      path: '/checkout'
      fullPath: '/checkout/'
      preLoaderRoute: typeof CheckoutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$productId': {
      id: '/product/$productId'
      path: '/product/$productId'
      fullPath: '/product/$productId'
      preLoaderRoute: typeof ProductProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/authenticate': {
      id: '/_auth/authenticate'
      path: '/authenticate'
      fullPath: '/authenticate'
      preLoaderRoute: typeof AuthAuthenticateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payment/esewa/success': {
      id: '/api/payment/esewa/success'
      path: '/api/payment/esewa/success'
      fullPath: '/api/payment/esewa/success'
      preLoaderRoute: typeof ApiPaymentEsewaSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payment/esewa/failure': {
      id: '/api/payment/esewa/failure'
      path: '/api/payment/esewa/failure'
      fullPath: '/api/payment/esewa/failure'
      preLoaderRoute: typeof ApiPaymentEsewaFailureRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PaymentFailedRoute: PaymentFailedRoute,
  PaymentSuccessRoute: PaymentSuccessRoute,
  AuthAuthenticateRoute: AuthAuthenticateRoute,
  ProductProductIdRoute: ProductProductIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  CheckoutIndexRoute: CheckoutIndexRoute,
  FavouriteIndexRoute: FavouriteIndexRoute,
  OrderIndexRoute: OrderIndexRoute,
  ProductIndexRoute: ProductIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiPaymentEsewaFailureRoute: ApiPaymentEsewaFailureRoute,
  ApiPaymentEsewaSuccessRoute: ApiPaymentEsewaSuccessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
